pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh './scripts/build.sh'
            }
        }
        stage('Test') {
            steps {
                sh './scripts/test.sh'
            }
        }
        stage('Deploy to Staging') {
            steps {
                sh './scripts/deploy-staging.sh'
            }
        }
    }
}
