name: CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag my-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ github.ref_name }}

      - name: Deploy to Staging
        run: chmod +x scripts/deploy-staging.sh && ./scripts/deploy-staging.sh
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_STAGING }}

      - name: Deploy to Production
        if: github.ref == 'refs/tags/v*'
        run: chmod +x scripts/deploy-production.sh && ./scripts/deploy-production.sh
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_PRODUCTION }}
0